name: Build

on:
  push:
    branches:
      - '*'
    tags-ignore:
      - '*'
  pull_request_target:

env:
  HUB_REPO: flighttrackr
  HUB_IMAGE: readsb
  LABEL_MAINTAINER: Dennis Neufeld <git@dneufeld.net>
  LABEL_TITLE: readsb
  LABEL_DESCRIPTION: Dockerized Readsb
  LABEL_LICENSE: MIT

jobs:
  build:
    name: Build
    runs-on: ubuntu-20.04
    env:
      ARCHS: linux/amd64,linux/arm/v6,linux/arm/v7,linux/arm64,linux/386

    steps:
      - name: Checkout
        uses: actions/checkout@v2.4.0
        with:
          submodules: true

      - name: Get upstream commit
        id: upstream
        run: echo "::set-output name=commit::$(git rev-parse HEAD:upstream)"

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1.2.0
        with:
          platforms: ${{ env.ARCHS }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1.6.0

      - name: Set up Docker metadata
        id: meta
        uses: docker/metadata-action@v3.6.0
        with:
          images: ghcr.io/${{ env.HUB_REPO }}/${{ env.HUB_IMAGE }}
          tags: type=sha,format=long
          labels: |
            org.opencontainers.image.authors=${{ env.LABEL_MAINTAINER }}
            org.opencontainers.image.title=${{ env.LABEL_TITLE }}
            org.opencontainers.image.description=${{ env.LABEL_DESCRIPTION }}
            org.opencontainers.image.licenses=${{ env.LABEL_LICENSE }}

      - name: Build Docker image
        uses: docker/build-push-action@v2.7.0
        with:
          platforms: ${{ env.ARCHS }}
          pull: true
          push: false
          build-args: |
            UPSTREAM_COMMIT=${{ steps.upstream.outputs.commit }}
          cache-from: type=gha,scope=main
          cache-to: type=gha,scope=main
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.label }}
