name: Build and Release

on:
  push:
    branches:
      - 'main'
    tags:
      - 'v*'

env:
  HUB_REPO: flighttrackr
  HUB_IMAGE: readsb
  IMAGE_LABELS: |
    org.opencontainers.image.authors=Dennis Neufeld <git@dneufeld.net>
    org.opencontainers.image.title=Readsb
    org.opencontainers.image.description=Dockerized Readsb
    org.opencontainers.image.licenses=MIT

jobs:
  build:
    name: Build and Push
    runs-on: ubuntu-20.04
    env:
      ARCHS: linux/amd64,linux/arm/v6,linux/arm/v7,linux/arm64,linux/386
    outputs:
      version: ${{ steps.settings.outputs.version }}

    steps:
      - name: Checkout
        uses: actions/checkout@v2.4.0
        with:
          submodules: true

      - name: Set release settings
        id: settings
        run: >
          if [[ $GITHUB_REF == refs/tags/v* ]];
          then
            echo "::set-output name=version::${GITHUB_REF#refs/tags/v}"
            echo "::set-output name=tags::type=semver,pattern={{raw}}"
          else
            echo "::set-output name=version::${GITHUB_REF#refs/heads/}"
            echo "::set-output name=tags::type=edge"
          fi

      - name: Get upstream commit
        id: upstream
        run: echo "::set-output name=commit::$(git rev-parse HEAD:upstream)"

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1.2.0
        with:
          platforms: ${{ env.ARCHS }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1.6.0

      - name: Set up Docker metadata
        id: meta
        uses: docker/metadata-action@v3.6.0
        with:
          images: ghcr.io/${{ env.HUB_REPO }}/${{ env.HUB_IMAGE }}
          flavor: latest=auto
          tags: ${{ steps.settings.outputs.tags }}
          labels: ${{ env.IMAGE_LABELS }}

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1.10.0
        with:
          registry: ghcr.io
          username: ${{ env.HUB_REPO }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v2.7.0
        with:
          platforms: ${{ env.ARCHS }}
          pull: true
          push: true
          build-args: UPSTREAM_COMMIT=${{ steps.upstream.outputs.commit }}
          cache-from: type=gha,scope=main
          cache-to: type=gha,scope=main
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.label }}


  release:
    name: Release
    runs-on: ubuntu-20.04
    needs:
      - build
    if: startsWith(github.ref, 'refs/tags/v')

    steps:
      - name: Checkout
        uses: actions/checkout@v2.4.0
        with:
          submodules: true

      - name: Get Changelog entry
        id: changelog
        uses: mindsers/changelog-reader-action@v2.0.0
        with:
          version: ${{ needs.build.outputs.version }}
          path: ./CHANGELOG.md

      - name: Release to GitHub
        uses: ncipollo/release-action@v1.8.10
        with:
          name: Release v${{ steps.changelog.outputs.version }}
          body: ${{ steps.changelog.outputs.changes }}
          prerelease: ${{ steps.changelog.outputs.status == 'prereleased' }}
          draft: ${{ steps.changelog.outputs.status == 'unreleased' }}
          allowUpdates: true
          token: ${{ secrets.GITHUB_TOKEN }}
